### ISSUE TITLE
Integration with Logger

### ISSUE THREAD

**Issue by minhajuddin** [honeybadger-io/honeybadger-elixir#101]
Many elixir apps use `Logger.error` to capture critical errors. The Honeybadger client doesn't capture this information at the moment.

Adding a custom [Logger](https://hexdocs.pm/logger/Logger.html) backend for Honeybadger would allow users to start getting useful information straight away, without needing to add `Honeybadger.notify` in addition to `Logger.error`

https://github.com/onkel-dirtus/logger_file_backend is one of the implementations for a custom logger backend.

A few things to note while building this:

  1. Allow users to set the log level at which they want to track this
  2. Allow users to opt out of Honeybadger notifications for specific instances by passing in some flag, e.g. `Logger.error("Not very critical?", honeybadger: false)`

**Comment by sorentwo** [comment]
I like where your head's at! Reworking the logger was next up on my list. Specifically allowing it to respect metadata to disable logging, which will prevent #65.

**Comment by joshuap** [comment]
You're always several steps ahead of us, @sorentwo. xD That sounds great. Are you pretty confident that reworking the logger is the solution to #65? I was going to ask @minhajuddin to look into the infinite errors issue but if you think you've got it covered then we could work on something else so that we're not stepping on your toes. It would be great if we could get the fix for #65 into the next release (0.7.0).

**Comment by sorentwo** [comment]
I'm fairly confident it will fix the problem. I believe it is a combination of adding the report handler directly within `Honeybadger.start/2` and the way the current logger handles the `:error_report` event. A Logger backend should be simpler to implement and configure as well.

**Comment by joshuap** [comment]
@sorentwo sounds good! Is there anything we can help with? Any other preliminary work that needs to be done to support logging?

**Comment by sorentwo** [comment]
@joshuap Hmm. I did a spike on this and a ton of reading. It appears that we need two logger modules to achieve this:

1. The existing error logger, which gets events directly from Erlang.
2. A new logger backend that gets events from Elixir's logger.

Errors that pass through Elixir's Logger are normalized. The error itself and the stacktrace are converted into iodata, so there isn't any way to generate a meaningful stacktrace from it.

The official Logger module does a bit of supervisor wizardry to make sure backends get cleaned up when the application is stopping (or code is reloading, ala a hot reload). At a minimum there are some supervision and genevent updates that I'd like to make to try and prevent infinite errors.

**Comment by sorentwo** [comment]
What we eventually shipped is different than the original request here. Is this still a desired feature? It isn't something we would use, so I'm not a good judge.

**Comment by joshuap** [comment]
@sorentwo I'm not a good judge either. I don't think anyone else has specifically requested this feature, so I'm fine with holding off on it. I'll go ahead and close it. To future users: if you want this, plz comment/reopen!
