### ISSUE TITLE
Document supported versions of Elixir, OTP, Plug and Phoenix

### ISSUE THREAD

**Issue by minhajuddin** [honeybadger-io/honeybadger-elixir#110]
We have a few dependencies: Elixir, Erlang OTP, Plug and Phoenix. We should document them and also activate them in our TravisCI. @joshuap Do you have any thoughts on which versions of these should be supported? I can then work on changing the travis configuration and adding ability to test our package with different versions of plug/phoenix

**Comment by minhajuddin** [comment]
@joshuap Any thoughts on this?

I am thinking the following

OTP: 18+
Elixir: 1.2+
Phoenix: 1.0+
Plug: 1.0+

**Comment by minhajuddin** [comment]
I am just copying the build matrix from Phoenix, those defaults should be good enough for us.

**Comment by joshuap** [comment]
@minhajuddin wfm. 👍

**Comment by sorentwo** [comment]
In the other PR the matrix was updated to start at 1.3, right? That seems like a more reasonable oldest version (and it would let us use describe blocks!)
