### ISSUE TITLE
Send notices async.

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#12]
Maybe just spawn a `Task` for each of them?

**Comment by rbishop** [comment]
I kept going back and forth on this. All IO is non-blocking already and in the case of Plug/Phoenix it's happening in its own process. It might make sense to spawn a `Task` in the Logger though.

**Comment by joshuap** [comment]
In the case of Plug/Phoenix it seems to add some latency to response times (if I was reading things correctly). Would it currently block the response until the exception was reported? I can do some extra testing on that if it would help.

**Comment by rbishop** [comment]
Ah, you're right. Yes let's just fire off a Task then :+1:
