### ISSUE TITLE
Make plug an optional dependency

### ISSUE THREAD

**Issue by aaronrenner** [honeybadger-io/honeybadger-elixir#121]
I have several elixir applications where I'm using honeybadger, but they don't have a plug dependency. What would you think about making plug an optional dependency like Phoenix?

**Comment by sorentwo** [comment]
@aaronrenner I think that's a great idea. The plug integration needs a little overhaul as well, it isn't currently to customize or augment it.

**Comment by joshuap** [comment]
I'm all for this. Would accept a PR or am happy to implement as we have time.
