### ISSUE TITLE
Connection timeout after several weeks in long-running nodes

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#135]
A user reported this issue via a support ticket--they have a long-running process, and after a few weeks errors stop being reported and they see this error in their log:

```
10:25:39.368 [error] [Honeybadger] connection error: :connect_timeout
```

@minhajuddin can you think of any reasons why this could happen? I'll ask them to post any other relevant info here.

**Comment by joshuap** [comment]
Could it be related to https://github.com/benoitc/hackney/issues/462 ?

**Comment by sorentwo** [comment]
That looks like it could very well be the issue. We can update the requested version of hackney, but I imagine many applications will have other dependencies on older versions of hackney/http_poison.

**Comment by joshuap** [comment]
@sorentwo We're already locked to `~> 1.1`, so the user should be able to manually update to hackney 1.12, I think?

**Comment by sorentwo** [comment]
@joshuap Yes, they should be able to do that.

My point was that we can't lock to `1.12` specifically, as it may conflict with other deps. It is up to users to define a more specific version in their application.

**Comment by minhajuddin** [comment]
@joshuap Have you heard back from the reporter about the version of hackney, This has been an older version of hackney which has been fixed since.

**Comment by joshuap** [comment]
@minhajuddin I haven't, and I'm going to assume that this issue is fixed, or at least has a clear workaround: update to the latest version of hackney. :)
