### ISSUE TITLE
Make the json decoder configurable

### ISSUE THREAD

**Issue by tcoopman** [honeybadger-io/honeybadger-elixir#136]
[jason](https://github.com/michalmuskala/jason) is a new json encoder that phoenix supports as well (https://github.com/phoenixframework/phoenix/issues/2693).

It would be nice if this could be configured in honeybadger to use an other json decoder.

**Comment by sorentwo** [comment]
In all of my projects I've switched to Jason as well, totally on board with this 💯 

@joshuap @minhajuddin I'm happy to open a PR that switches the default to Jason and makes it configurable, what do you think?

**Comment by minhajuddin** [comment]
@tcoopman The fix for this swaps out the encoder for Jason.
