### ISSUE TITLE
No matching function clause Honeybadger.Backtrace.from_stacktrace/1

### ISSUE THREAD

**Issue by AnilRedshift** [honeybadger-io/honeybadger-elixir#149]
Hello,

I'm getting the following application logs:

> {"severity":"warn","msg":"Unable to notify Honeybadger! FunctionClauseError: no function clause matching in Honeybadger.Backtrace.from_stacktrace/1","appname":"phone-filtering"}

From looking at the source code, `stacktrace` [must not be a list](https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger/backtrace.ex#L22)?

I don't have any other debugging info to go on unfortunately. Our HB setup is the straightforward plug integration:

```
defmodule PhoneFilteringWeb.Router do
  use PhoneFilteringWeb, :router
  use Honeybadger.Plug

```

**Comment by minhajuddin** [comment]
@AnilRedshift Can you share your elixir,  erlang, honeybadger, plug and phoenix versions.

**Comment by AnilRedshift** [comment]
@minhajuddin:
elixir is 1.6.3
erlang is 20.2.4
honeybadger is 0.9.0
plug is 1.5
phoenix is 1.3.2

**Comment by sorentwo** [comment]
@AnilRedshift Do you happen to be calling `Honeybadger.notify` manually anywhere? The format returned by `System.get_stacktrace/0` and `Process.info/2` always returns a list of tuples, so I don't know how we would get anything that isn't a list.

**Comment by AnilRedshift** [comment]
Ah, yes we are
`Honeybadger.notify("Data is not found.", %{context: %{conn: inspect(conn)}})`

I'll try to force a repro of this tomorrow, but just from code inspection, it looks like the Honeybadger code is the one that [sets the stacktrace to nil](https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger.ex#L207)?


 `def notify(exception, metadata \\ %{}, stacktrace \\ nil) do`

**Comment by thmzlt** [comment]
Same here, adding the Honeybadger hex package and setting `use_logger: true` gets me the same error.

**Comment by sorentwo** [comment]
There must be a case where the error logger is getting passed `error_info` that has a stacktrace that isn't a list. I'd love to know _why_ that is happening, since to my knowledge that isn't documented.

@thmzlt Any idea what error is triggering it for you?

I can add guards and an additional clause to prevent failure when the `error_info` payload doesn't match. My only concern is that we'll lose the stacktrace in doing that.

**Comment by sorentwo** [comment]
I've prepared a fix for this issue using a contrived test example.

@AnilRedshift @thmzlt Please take a look at #150 and give it a try.
