### ISSUE TITLE
Parallel Compiler issue

### ISSUE THREAD

**Issue by nihalgonsalves** [honeybadger-io/honeybadger-elixir#164]
I get this compilation error when compiling my deps:

```
== Compilation error in file lib/api/router.ex ==
** (CompileError) lib/my_app/router.ex:5: module Honeybadger.Plug is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/my_app/router.ex:5: API.Router (module)
    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

It may be related to https://github.com/elixir-lang/elixir/issues/7699 or https://github.com/getsentry/sentry-elixir/issues/232

This happened right after fixing a similar problem with `Sentry.Plug`

**Comment by minhajuddin** [comment]
I am trying to reproduce this without any luck, I've used https://github.com/honeybadger-io/crywolf-elixir as a test project. @nihalgonsalves Are you able to consistently reproduce this? Can you share your version info? Elixir, Erlang, Plug and Honeybadger versions.

**Comment by sorentwo** [comment]
If you follow the chain links through the linked issues you'll find https://github.com/elixir-lang/elixir/pull/7833. This was fixed four days ago and will be released with Elixir 1.7.

**Comment by nihalgonsalves** [comment]
A few changes later I reverted the removal of `Honeybadger.Plug` and now it works for me as well, on `1.6.5`. Looks like something transient/random. Thanks anyway!

**Comment by joshuap** [comment]
Thanks everyone!
