### ISSUE TITLE
Video in README.md has an error.

### ISSUE THREAD

**Issue by MichaelDimmitt** [honeybadger-io/honeybadger-elixir#183]
Going to the link: 
https://josh-rubyist.wistia.com/medias/pggpan0f9j

Produces error: 
`This account has been cancelled. If you are the account's owner, you may login here to choose a plan and reactivate this account.`

**Comment by sorentwo** [comment]
Nothing I can do for this one, /cc @joshuap

**Comment by MichaelDimmitt** [comment]
working again 🎉
