### ISSUE TITLE
Is it possible to ignore crashes of a specific GenServer while still having `use_logger` true?

### ISSUE THREAD

**Issue by tcoopman** [honeybadger-io/honeybadger-elixir#190]
The title basically says it all. I want to ignore a crash from a specific GenServer (external dependency that I have no control over). I think with the new `Logger` that it should be possible to ignore it with filters on the logger, but so far I haven't found anything in `sasl` or `error_logger`.

So I was wondering if there was an other way to ignore the error?

**Comment by sorentwo** [comment]
There currently isn't any way to filter errors that come through the error logger. A crash report would be too generic to match on anyhow. Without filtering based on additional context or process state you would probably ignore far more errors than you intended.

You can pause or ignore the error directly within the Honeybadger UI.

**Comment by tcoopman** [comment]
The problem with the Honeybadger UI is that you can't pause/ignore an error based on an environment as far as I can see.

**Comment by stympy** [comment]
Since errors are grouped by environment, you can ignore an error based on environment.
