### ISSUE TITLE
Handle API responses and report if unable to post error

### ISSUE THREAD

**Issue by muhmi** [honeybadger-io/honeybadger-elixir#20]
Hi!

It would be nice if you would check API responses and report through Logger if you cannot post to honeybadger or retry a couple of times.

**Comment by joshuap** [comment]
Agreed! Our API responds with a 201 when the notice was created. I would log an error message w/ the returned status code for any non-20x status.

**Comment by nurugger07** [comment]
@muhmi this will be coming in the v0.7 release later this week

**Comment by joshuap** [comment]
This is added in 0.7.0-beta, which has been released (stable release should happen soon).
