### ISSUE TITLE
Pass revision of current deploy?

### ISSUE THREAD

**Issue by thomasbrus** [honeybadger-io/honeybadger-elixir#207]
Is it possible to pass the revision of the current deploy? I couldn't find anything in the docs or in the code. 

Both the Ruby & JS version support a `:revision` config option: 
- https://docs.honeybadger.io/ruby/gem-reference/configuration.html
- https://docs.honeybadger.io/lib/javascript/reference/configuration.html

**Comment by joshuap** [comment]
@thomasbrus it doesn't look like we support this feature yet. I'm open to PRs for it, though. I think it would require adding a `revision` configuration option, and then sending that option in the API payload similar to [how we do for Ruby](https://github.com/honeybadger-io/honeybadger-ruby/blob/35d210bb2a97ab3d19c892defa40c0854a0ebe50/lib/honeybadger/notice.rb#L215).

**Comment by thomasbrus** [comment]
I'll have a look at it soon-ish!
