### ISSUE TITLE
Is there a reason not to call `Exception.blame` automatically?

### ISSUE THREAD

**Issue by axelson** [honeybadger-io/honeybadger-elixir#211]
Is there a specific reason that `Exception.blame/3` is not called automatically by Honeybadger? It does say that "This operation is potentially expensive, as it reads data from the file system, parses beam files, evaluates code and so on." but I think this should at least be optional when using honeybadger since it provides a much richer error.

It can convert an error like this:
```
no function clause matching in Messages.handle_message_created/2
```

into:
```
no function clause matching in Messages.build_notifications/3

The following arguments were given to Messages.build_notifications/3:

    # 1
    %Chat.Message{__meta__: #Ecto.Schema.Metadata<:loaded, "messages">, ...snip large struct value}

    # 2
    nil

    # 3
    nil

Attempted function clauses (showing 3 out of 3):

    def build_notifications(message, thread, -%Messages.MessageContainer.MessageContainerImpl{container_id: post_id}-)
    def build_notifications(%{id: message_id}, _thread, -%Communities.Post{message_id: message_id}-)
    def build_notifications(message, thread, -%Communities.Post{} = post-)
```

Might be related to #123

**Comment by sorentwo** [comment]
@axelson There isn't a good reason at this point. Historically the primary reason is that we don't require a `kind` argument for `notify/3` and we treat all exceptions like an `error` when normalizing.

I think it would be a good change to get in though. I can look into it next week, or if you're interested a PR is certainly welcome =)

**Comment by axelson** [comment]
This would be really useful for us so I've created a PR #219
