### ISSUE TITLE
Release 0.12

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#222]
This issue is to track the release of 0.12.0. We currently have 2 unreleased additions in the CHANGELOG. Let me know if there's anything we're missing, @sorentwo. Otherwise I'll plan to cut the release in in a few days. Thanks!

**Comment by sorentwo** [comment]
@joshuap I took a look through the commits and it looks like everything is covered in the CHANGELOG. Before we get 0.12 out it would be great to have Erlang/OTP 22 in the build matrix.

Note: PR for OTP 22 is here #223

**Comment by joshuap** [comment]
Thanks @sorentwo! Merged that. I'll release by the end of the week.

**Comment by joshuap** [comment]
:shipit: https://hex.pm/packages/honeybadger/0.12.0
