### ISSUE TITLE
Exception.blame being called on notify when noticeable is not an Exception

### ISSUE THREAD

**Issue by steve-pieris** [honeybadger-io/honeybadger-elixir#225]
After upgrading to v0.12, When Notify is called with a string, eg `Honeybadger.notify("some message")`,  the message is being reported as an Erlang Error. 

Should `Exception.blame` be called when the exception parameter is not an Exception?
Note: the parameter can be of type `Notify.noticeable{}` which includes Exception, string, map or atoms.

**Comment by sorentwo** [comment]
Thanks for the report. I'm working on this one now 👍
