### ISSUE TITLE
Feature Request: Include attempted function clauses in error reports when applicable

### ISSUE THREAD

**Issue by starbelly** [honeybadger-io/honeybadger-elixir#228]
As a user of honey badger, when an exception happens in my application involving incorrect arguments then the error report for the exception should include the attempted function clause output so I can quickly diagnose the problem at hand. 

# Example

## Current behavior

Given a the operation `Decimal.mult(1, nil)` I only see the following in an error report:

```erlang
no function clause matching in Decimal.decimal/1
```

## New behavior

```erlang
** (FunctionClauseError) no function clause matching in Decimal.decimal/1

    The following arguments were given to Decimal.decimal/1:

        # 1
        nil

    Attempted function clauses (showing 4 out of 4):

        defp decimal(%Decimal{} = num)
        defp decimal(num) when is_integer(num)
        defp decimal(num) when is_binary(num)
        defp decimal(other) when is_float(other)

    (decimal) lib/decimal.ex:1816: Decimal.decimal/1
    (decimal) lib/decimal.ex:971: Decimal.mult/2
```

Per the above I see the arguments given as well as the attempted function clauses.

**Comment by sorentwo** [comment]
@starbelly Which version of honeybadger-elixir are you using? As of 0.12 all exceptions are passed through `Exception.blame/3` and should have the most detailed exception information available.

**Comment by starbelly** [comment]
@sorentwo 0.11.0 - so it sounds like this ticket can be closed.

**Comment by sorentwo** [comment]
Great to hear it. Upgrade to 0.12.1 and you’ll be all set.
