### ISSUE TITLE
GenServer error reporting fails in weird way

### ISSUE THREAD

**Issue by muhmi** [honeybadger-io/honeybadger-elixir#24]
Hi I got this error in my logs:
```
** (Protocol.UndefinedError) protocol Enumerable not implemented for {GenServer, :call, [#PID<0.1911.0>, {:poll_notifications}, 5000]}
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:140: Enumerable.count/1
    (elixir) lib/enum.ex:437: Enum.count/1
    (honeybadger) lib/honeybadger.ex:135: Honeybadger.do_notify/3
    (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<0.12943092/0 in Honeybadger.Logger.handle_event/2>
    Args: []

=CRASH REPORT==== 27-Oct-2015::08:01:07 ===
  crasher:
    initial call: Elixir.Honeybadger.Logger:-handle_event/2-fun-0-/0
    pid: <0.1237.0>
    registered_name: []
    exception exit: {#{'__exception__' => true,
                       '__struct__' => 'Elixir.Protocol.UndefinedError',
                       description => nil,
                       protocol => 'Elixir.Enumerable',
                       value => {'Elixir.GenServer',call,
                           [<0.1911.0>,{poll_notifications},5000]}},
                     [{'Elixir.Enumerable','impl_for!',1,
                          [{file,"lib/enum.ex"},{line,1}]},
                      {'Elixir.Enumerable',count,1,
                          [{file,"lib/enum.ex"},{line,140}]},
                      {'Elixir.Enum',count,1,
                          [{file,"lib/enum.ex"},{line,437}]},
                      {'Elixir.Honeybadger',do_notify,3,
                          [{file,"lib/honeybadger.ex"},{line,135}]},
                      {'Elixir.Task.Supervised',do_apply,2,
                          [{file,"lib/task/supervised.ex"},{line,74}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,240}]}]}
      in function  'Elixir.Task.Supervised':exit/4 (lib/task/supervised.ex, line 105)
    ancestors: [error_logger,<0.2.0>]
    messages: []
    links: []
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 151
  neighbours:
```

Not sure whats the root cause it appeared after I had restarted my application server and received an error like this:
```
2015-10-27 08:01:07.859 [error] Discarding message {'$gen_call',{<0.1236.0>,#Ref<0.0.1.757>},{poll_notifications}} from <0.1236.0> to <0.1911.0> in an old incarnation (1) of this node (2)



=CRASH REPORT==== 27-Oct-2015::08:01:07 ===
  crasher:
    initial call: Elixir.Giger.Player:init/1
    pid: <0.1236.0>
    registered_name: []
    exception exit: {noproc,
                        {'Elixir.GenServer',call,
                            [<0.1911.0>,{poll_notifications},5000]}}
      in function  gen_fsm:init_it/6 (gen_fsm.erl, line 396)
    ancestors: [<0.1229.0>]
    messages: []
    links: [<0.1229.0>]
    dictionary: [{'$relock_lock',
                      #{'__struct__' => 'Elixir.Relocker.Lock',
                        lease_time => 10,
                        metadata => #{node => 'giger@ip-172-31-49-111.ec2.internal',
                          pid => <0.1236.0>},
                        name => <<"user:XC4MNHOl">>,
                        secret => <<"yMzDZ0RFqdVPjJ5RUyNQ4xHffErPXsi2LIne5m+L24g=">>,
                        valid_until => 1445932877}},
                  {random_seed,{24548,13903,23315}},
                  {logger_metadata,
                      {true,
                          [{userid,<<"user:XC4MNHOl">>},{id,"<0.1236.0>"}]}}]
    trap_exit: false
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 363946
...
```

Any idea what this could be?

Cheers,

Roope

**Comment by joshuap** [comment]
It looks like whatever is being passed in as `stacktrace` [here](https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger.ex#L133) does not define Enumerable, which makes sense since it looks like the stacktrace is a tuple. Do you happen to have any example code which can reproduce this?

**Comment by rbishop** [comment]
Yeah the `stacktrace` is a tuple of `{module, function, args}` which seems unusual for an error report. I'd also like to know how to reproduce this because that looks like a tuple you would pass to `apply/3`.

**Comment by muhmi** [comment]
Hi!

Sorry guys I got this while rebooting our game server. I can try to isolate
that somehow if I can.

Have you tested the lib with GenServers? Or should one use this lib for
other than phoenix web stuff.

--
Roope

**Comment by muhmi** [comment]
Hmm,

There seems to be two kind of `error_report` events http://www.erlang.org/doc/man/error_logger.html#events. 

And also the Report can be a few things http://www.erlang.org/doc/man/error_logger.html#type-report

Maybe you should just narrow down the handle_event to match exactly the kinds of cases that handler can format?

Just a side note, would it make any sense add support for using a Logger backend to push all error easily to honeybadger?

**Comment by rbishop** [comment]
We should be handling all of the `:error_report` matches with this: https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger/logger.ex#L19-L20

With regard to not using `Logger`: I originally tried to but Elixir's Logger uses a Translator that turns everything (exception, message, stacktrace) into a String and doesn't give you access to other things like the process dictionary. We could remove that translator but that would be surprising to a lot of people because it is used for writing to log files.

**Comment by rbishop** [comment]
I've been meaning to write up a proposal to the Logger project about making Translators be Backend specific but haven't had the time.

**Comment by muhmi** [comment]
Still at least for a game developer like me being able to track errors with strings like "oh my, this should never happen" and just grab the logger metadata.Would be really helpful, I still do that my self too - not a problem.   (Could have things like user_id etc that are useful)

But yeah, loosing the stacktrace is bad. But in this case its more maybe about knowing that "oh my" happens to players 1, 2 and 7. I do have some stats I can track about amounts of things going on and can process through the logs to find out more context about erros so this is not a big issue.

This is the kind of simple firehose to chat approach we'd use now to get stuff from Logger: https://github.com/tsharju/flowdock_logger/blob/master/lib/flowdock_logger.ex#L54

**Comment by rbishop** [comment]
You can still use `Logger.error/warn/info/debug` but those won't go to Honeybadger. You can call `Honeybadger.notify` to manually report to Honeybadger, however. Here is some documentation on how to do that: https://github.com/honeybadger-io/honeybadger-elixir#honeybadgernotify-send-an-exception-to-honeybadger

**Comment by muhmi** [comment]
Yeah,

Thanks. I am now using Honeybadger.notify manually in one case to report exceptions when handing messages from websocket.

The thing I was after was to actually push those Logger.error lines to honeybadger too but, yeah maybe that is not the correct place for those since they are not exceptions.

**Comment by rbishop** [comment]
Adding this guard should handle these stray messages: https://github.com/honeybadger-io/honeybadger-elixir/pull/25

Though it still does not address the greater issue of why is something non-exception like a GenServer.call getting sent  as an error_report to the error_logger :/ I'll have to dig into error_logger to try and figure that out.

**Comment by joshuap** [comment]
@muhmi in the cases where you would log an error message, would it be possible to just raise an exception instead? Just wondering about the use case. We do support logging more arbitrary error messages in our Ruby and most other libraries. In Ruby, at least you have access to `caller` which we use to construct a backtrace and basically coerce the error message into an exception-like object for reporting. It looks like the equivalent in Elixir might be `:erlang.get_stacktrace` -- maybe we could do something similar. In our ruby gem we support something like `Honeybadger.notify(error_message: "this should never happen!")`.

@rbishop agreed it would be nice to uncover the root cause here; I'm fine with #25 if you think it's appropriate, though.

**Comment by muhmi** [comment]
@joshuap Granted - the case where I would log things like "oh my something went wrong but continuing anyway" is uncommon.  I will think about this and make a separate issue for the feature request if I truly have a use case for it. 

One example is a GenServer calling some external API, I dont want to take it down because one call explodes and loose the inbox. There I could be using the GenServer to throttle calls towards the API etc.

Anyway, I will now run both honeybadger and a custom logger backend on the server and see that all errors actually get propagated to honeybadger (though error_logger). If not I will make another issue =)

Thanks guys for the awesome support!

**Comment by joshuap** [comment]
Anytime, thanks for the debugging! :)

**Comment by muhmi** [comment]
Another example:
```
2015-10-29 08:03:16.535 [error] Task #PID<0.1364.0> started from :error_logger terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {GenServer, :call, [League.Service, {:status, "user:4kIMGvny", %Timex.DateTime{calendar: :gregorian, day: 29, hour: 8, minute: 3, month: 10, ms: 251, second: 16, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2015}}, 5000]}
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:140: Enumerable.count/1
    (elixir) lib/enum.ex:437: Enum.count/1
    (honeybadger) lib/honeybadger.ex:135: Honeybadger.do_notify/3
    (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<0.12943092/0 in Honeybadger.Logger.handle_event/2>
    Args: []

=CRASH REPORT==== 29-Oct-2015::08:03:16 ===
  crasher:
    initial call: Elixir.Honeybadger.Logger:-handle_event/2-fun-0-/0
    pid: <0.1364.0>
    registered_name: []
    exception exit: {#{'__exception__' => true,
                       '__struct__' => 'Elixir.Protocol.UndefinedError',
                       description => nil,
                       protocol => 'Elixir.Enumerable',
                       value => {'Elixir.GenServer',call,
                           ['Elixir.League.Service',
                            {status,<<"user:4kIMGvny">>,
                                #{'__struct__' => 'Elixir.Timex.DateTime',
                                  calendar => gregorian,
                                  day => 29,
                                  hour => 8,
                                  minute => 3,
                                  month => 10,
                                  ms => 251,
                                  second => 16,
                                  timezone => #{'__struct__' => 'Elixir.Timex.TimezoneInfo',
                                    abbreviation => <<"UTC">>,
                                    from => min,
                                    full_name => <<"UTC">>,
                                    offset_std => 0,
                                    offset_utc => 0,
                                    until => max},
                                  year => 2015}},
                            5000]}},
                     [{'Elixir.Enumerable','impl_for!',1,
                          [{file,"lib/enum.ex"},{line,1}]},
                      {'Elixir.Enumerable',count,1,
                          [{file,"lib/enum.ex"},{line,140}]},
                      {'Elixir.Enum',count,1,
                          [{file,"lib/enum.ex"},{line,437}]},
                      {'Elixir.Honeybadger',do_notify,3,
                          [{file,"lib/honeybadger.ex"},{line,135}]},
                      {'Elixir.Task.Supervised',do_apply,2,
                          [{file,"lib/task/supervised.ex"},{line,74}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,240}]}]}
      in function  'Elixir.Task.Supervised':exit/4 (lib/task/supervised.ex, line 105)
    ancestors: [error_logger,<0.2.0>]
    messages: []
    links: []
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 540
  neighbours:
2015-10-29 08:03:19.864 module=Giger.Player line=1619 id=<0.1332.0> userid=user:0pCreb6I [debug] Ping pong took 107.287 ms.
```
