### ISSUE TITLE
Logger.metadata does not show up in context when calling Honeybadger.notify

### ISSUE THREAD

**Issue by JediLuke** [honeybadger-io/honeybadger-elixir#256]
I hav found previous issues where this seems to be addressed

https://github.com/honeybadger-io/honeybadger-elixir/issues/19
https://github.com/honeybadger-io/honeybadger-elixir/issues/176

But in 0.13 I seem to be getting this behaviour again - when calling Honeybadger.notify, the `Logger.metadata` is not automatically being added to the Honeybadger context when I call Honeybadger.notify

**Comment by joshuap** [comment]
@JediLuke thanks for the report. I'm not sure what might be causing this off the top of my head. Do you have any idea, @sorentwo?

**Comment by sorentwo** [comment]
My guess is that `Honeybadger.notify` is getting called from a separate process. `Logger.metadata` is set per-process and isn't global, so it won't show up in reports from tasks or other processes that may error during a request.

This demonstrates the situation in iex:

```
iex(2)> Logger.metadata(foo: "bar")
:ok
iex(3)> Logger.metadata()
[foo: "bar"]
iex(4)> Task.async(fn -> Logger.metadata() end) |> Task.await()
[]
```

There isn't anything (sane) we can do to grab that metadata in a separate process.
