### ISSUE TITLE
ELIXIR 1.1.0.0 breaking changes

### ISSUE THREAD

**Issue by ahsandar** [honeybadger-io/honeybadger-elixir#258]
`Honeybadger` is not compliant with `elixir 1.10.0` seems some design choices should not have been made please refer to the below thread for details pointed out by `Jose Valim` over the issue in `honeybadger-elixir`
https://elixirforum.com/t/elixir-v1-10-0-released/28609/40?u=darnahsan

**Comment by sorentwo** [comment]
Thanks for the report! Closing in favor of #259
