### ISSUE TITLE
Client has unhandled encoding errors

### ISSUE THREAD

**Issue by kennethito** [honeybadger-io/honeybadger-elixir#261]
[handle_cast notice](https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger/client.ex#L131) does not handle `%Protocol.UndefinedError`, which is the result I get for unencodable notices.  Enough of these errors can lead to the honeybadger app crashing and taking down the main application.

```
Honeybadger.JSON.encode(%{ test: fn () -> :noop end })
{:error,
 %Protocol.UndefinedError{
   description: "Jason.Encoder protocol must always be explicitly implemented",
   protocol: Jason.Encoder,
   value: #Function<20.99386804/0 in :erl_eval.expr/5>
 }}
```

**Comment by sorentwo** [comment]
Closing in favor of the PR.
