### ISSUE TITLE
Do not add report handler when in excluded env

### ISSUE THREAD

**Issue by muhmi** [honeybadger-io/honeybadger-elixir#27]
Hi!

It seems you are adding the report handler always, even when running in a environment where I do not want to use the library. 

In situations like running load tests I would appreciate that I could totally disable integrations like honeybadger. Just to avoid sending 10k reports. I can do that by making sure the library is not in my `:applications` list but its more convenient if the `:exclude_envs` would disable also the logger.

This is an issue because of `Honeybadger.Logger` exploding when handling some error reports. 
See: https://github.com/honeybadger-io/honeybadger-elixir/issues/24

**Comment by rbishop** [comment]
As long as your env is in `excluded_envs` Honeybadger.notify gets turned into a no-op which means the reports don't actually get sent. It is an interesting thought to just not add the error handler at all if current env is in excluded_env. I'm sure there isn't any harm in doing that.

**Comment by joshuap** [comment]
I prefer to no-op the connectivity part but leave the rest of the logic intact in tests; it causes more of our code to be covered in your test suite which exposes issues earlier (like the logger exploding :)).

**Comment by muhmi** [comment]
@joshuap I see your point =) I will just change the behaviour in my fork until issue #24 is fixed =)
