### ISSUE TITLE
Move CI to GitHub Actions

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#282]

**Comment by sorentwo** [comment]
@joshuap There is a good base for this in [oban](https://github.com/sorentwo/oban/blob/master/.github/workflows/ci.yml)

**Comment by joshuap** [comment]
This is done, although the new action is not running dialyzer. We can add that if it's necessary (I looked into it briefly and couldn't figure out how to do it properly w/ GH Actions).
