### ISSUE TITLE
Protocol.UndefinedError for %Honeybadger.Breadcrumbs.RingBuffer

### ISSUE THREAD

**Issue by rabidpraxis** [honeybadger-io/honeybadger-elixir#293]
We received a support request where `Honeybadger.Breadcrumbs.RingBuffer` is attempting to be serialized by Jason. It looks like the error is coming from the library `logger_json` outputting the logger metadata as a log event. We use the logger metadata to store the RingBuffer as a convenience because it stays alongside the calling process. It was never meant to be output directly, as we extract the data before we notify.

Since we can't control who uses the logger metadata one way to solve this is to implement the Jason.Encoder protocol for RingBuffer.

**Comment by sorentwo** [comment]
Closed by #294
