### ISSUE TITLE
OTP 22 builds failing

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#298]
It looks like the OTP 22 builds started failing after https://github.com/honeybadger-io/honeybadger-elixir/commit/9b6a78220eca04d6ac45a433262303eeb9589b33. OTP 21.2 passes. I've experienced some issues with Travis failing to add checks to PRs lately--I wonder if that's happening here.

Builds: https://travis-ci.org/github/honeybadger-io/honeybadger-elixir/builds

**Comment by sorentwo** [comment]
I’ve experienced similar issues with that Ecto version locally. I’m not sure this is really a bug for us, but I’ll take a look at it.

**Comment by sorentwo** [comment]
This is a bug in OTP 22 that is fixed with newer releases: https://elixirforum.com/t/ecto-no-longer-compiles-after-upgrading-to-elang-otp-22/32467/3?u=sorentwo
