### ISSUE TITLE
Do we need a top-level supervisor?

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#32]
I tried updating honeybadger in a mix project and then releasing with exrm, and ran into an error similar to this: https://github.com/bitwalker/exrm/issues/183

Could it be that we have the same problem?

**Comment by parubets** [comment]
same problem for me...

**Comment by joshuap** [comment]
@parubets thanks, we'll look into this. @rbishop didn't we fix the top-level supervisor issue? Any ideas what could be going on here?

**Comment by joshuap** [comment]
#37 should fix this issue. @parubets let me know if you still have the issue after updating to 0.5.0.
