### ISSUE TITLE
Document error grouping and fingerprint options

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#338]
The docs (in [README.MD](./README.MD) are lacking information about error grouping, and how to use the `fingerprint` option/`FingerprintAdapter`. Could we add a section and/or flesh out the API docs on that?

Related:

https://github.com/honeybadger-io/honeybadger-elixir/issues/308#issuecomment-782332124
https://docs.honeybadger.io/lib/ruby/getting-started/customizing-error-grouping.html

**Comment by TraceyOnim** [comment]
@joshuap The API docs have a clear explanation of error grouping. Will it be okay if we add the API doc link in README.md ? Check out the [PR](https://github.com/honeybadger-io/honeybadger-elixir/pull/376/files) I have added
