### ISSUE TITLE
README incorrect regarding default environment_name

### ISSUE THREAD

**Issue by abstractcoder** [honeybadger-io/honeybadger-elixir#341]
The README mentions that environment_name will default to Mix.env(), but it will always defaults to :prod if it is not set. The reason why is alluded to in the CHANGELOG for version 0.4.0 (Mix.env() always defaults to :prod for dependencies).

**Comment by AdamT** [comment]
Just discovered this as well. One must specify `environment_name: Mix.env()` for `exclude_envs` to not raise errors in `:dev`/`:test`
