### ISSUE TITLE
Custom filter_cgi_data/1 never called

### ISSUE THREAD

**Issue by mbklein** [honeybadger-io/honeybadger-elixir#350]
I've been trying to write a custom filter to handle `cgi_data` a little differently than the default, and I noticed that my overridden `filter_cgi_data/1` was not being called. After a little poking around, I found that as of #105, the configured filter is [skipped for `cgi_data` in the default `NoticeFilter`](https://github.com/honeybadger-io/honeybadger-elixir/blob/v0.16.0/lib/honeybadger/notice_filter/default.ex#L21), with no way to override it.

I know I can write my own `NoticeFilter`, but that seems like overkill when I'm trying to do something using a specific, documented behaviour/callback.

**Comment by joshuap** [comment]
Thanks @mbklein, we'll take a look.

cc @sorentwo

**Comment by alanmf** [comment]
Any idea on a timeline for this? I'm having this issue with filter_cgi_data as well

**Comment by joshuap** [comment]
I tried fixing this in #353. I don't have an ETA on a release yet, but hopefully not very long.

**Comment by joshuap** [comment]
The fix for this has been released in 0.16.1
