### ISSUE TITLE
"FunctionClauseError: no function clause matching in Jason.Encode.list_loop/3" from HB reporting

### ISSUE THREAD

**Issue by henrik** [honeybadger-io/honeybadger-elixir#356]
I saw this error logged here: https://app.honeybadger.io/projects/72231/faults/78372903

The backtrace makes me think our app had a DB connection error but Honeybadger's reporting encountered an error trying to show that error, and reported its own error instead.

Message:

```
no function clause matching in Jason.Encode.list_loop/3

The following arguments were given to Jason.Encode.list_loop/3:

    # 1
    "** (DBConnection.ConnectionError) ssl recv: timeout"

    # 2
    #Function<3.48815102/3 in Jason.Encode."-fun.escape_json/3-">

    # 3
    #Function<1.48815102/3 in Jason.Encode."-fun.map_naive/3-">

Attempted function clauses (showing 2 out of 2):

    defp list_loop(-[]-, _escape, _encode_map)
    defp list_loop(-[head | tail]-, escape, encode_map)
```

Backtrace:

```
no function clause matching in Jason.Encode.list_loop/3 The following arguments were given to Jason.Encode.list_loop/3: # 1 "** (DBConnection.ConnectionError) ssl recv: timeout" # 2 #Function<3.48815102/3 in Jason.Encode."-fun.escape_json/3-"> # 3 #Function<1.48815102/3 in Jason.Encode."-fun.map_naive/3-"> Attempted function clauses (showing 2 out of 2): defp list_loop(-[]-, _escape, _encode_map) defp list_loop(-[head | tail]-, escape, encode_map)
lib/encode.ex:147:in `list_loop/3'
lib/encode.ex:153:in `list_loop/3'
lib/encode.ex:144:in `list/3'
lib/encode.ex:182:in `map_naive_loop/3'
lib/encode.ex:183:in `map_naive_loop/3'
lib/encode.ex:173:in `map_naive/3'
lib/honeybadger/notice.ex:40:in `encode/2'
lib/encode.ex:35:in `encode/2'
````

**Comment by sorentwo** [comment]
Strange. All of the notice output is escaped or inspected to guard against encoding issues: https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger/json.ex

I've seen plenty of `DBConnection.ConnectionError` errors reported before. Is this a one off for you?

**Comment by henrik** [comment]
Thank you. No, afraid not. Has happened 16 times so far.

**Comment by henrik** [comment]
We get some "DBConnection.ConnectionError" as well. Most recently 9 days ago.

The project we get these errors in is open source, by the way: https://github.com/barsoom/ex-remit It's currently using 0.16.0 of the Honeybadger hex package (= latest).

Looking back through instances of this error in HB, some are not DBConnection.ConnectionErrors, like this one:

```
no function clause matching in Jason.Encode.list_loop/3

The following arguments were given to Jason.Encode.list_loop/3:

    # 1
    "tcp connect: timeout"

    # 2
    #Function<3.48815102/3 in Jason.Encode."-fun.escape_json/3-">

    # 3
    #Function<1.48815102/3 in Jason.Encode."-fun.map_naive/3-">

Attempted function clauses (showing 2 out of 2):

    defp list_loop(-[]-, _escape, _encode_map)
    defp list_loop(-[head | tail]-, escape, encode_map)
```

**Comment by sorentwo** [comment]
After updating the oban pro site to v0.16 I'm also seeing the same error. It's definitely a change in the past couple of versions. I'll bisect and find it next week.

**Comment by bayprogrammer** [comment]
> Strange. All of the notice output is escaped or inspected to guard against encoding issues: https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger/json.ex
> 
> I've seen plenty of `DBConnection.ConnectionError` errors reported before. Is this a one off for you?

For what it's worth, we discovered that an improper list was making its way to Jason causing it to croak. When the improper list is looped over then `Jason.Encode.list_loop/3` is (attempted to be?) called like this:

```
Jason.Encode.list_loop(
  "** (DBConnection.ConnectionError) client #PID<0.13342.9> timed out because it checked out the connection for longer than 15000ms",
  #Function<2.132617835/3 in Jason.Encode.escape_function/1>,
  #Function<0.132617835/3 in Jason.Encode.encode_map_function/1>
)
```

And there is no implementation for `list_loop/3` which accepts a binary as the first parameter (leading to the errors we've seen).

I haven't been able to determine how that improper list is created in the first place, but something like this was making its way to Honeybadger (you can past that straight into `iex` and poke at it):

```
{
  :"$gen_cast",
  {
    :notice,
    %Honeybadger.Notice{
      breadcrumbs: %{
        enabled: true,
        trail: [
          %Honeybadger.Breadcrumbs.Breadcrumb{
            category: "error",
            message: "RuntimeError",
            metadata: %{
              message: "[DEPTH]"
            },
            timestamp: %DateTime{
              year: 2021,
              month: 04,
              day: 13,
              hour: 02,
              minute: 31,
              second: 34,
              microsecond: {407911, 6},
              utc_offset: 0,
              time_zone: "Etc/UTC",
              zone_abbr: "UTC",
              std_offset: 0
            }
          },
          %Honeybadger.Breadcrumbs.Breadcrumb{
            category: "notice",
            message: "Honeybadger Notice",
            metadata: %{},
            timestamp: %DateTime{
              year: 2021,
              month: 04,
              day: 13,
              hour: 02,
              minute: 31,
              second: 34,
              microsecond: {407973, 6},
              utc_offset: 0,
              time_zone: "Etc/UTC",
              zone_abbr: "UTC",
              std_offset: 0
            }
          }
        ]
      },
      error: %{
        backtrace: [],
        class: "RuntimeError",
        fingerprint: "",
        message: [
          "Postgrex.Protocol",
          32,
          40,
          "#PID<0.394.0>",
          ") disconnected: "
            | "** (DBConnection.ConnectionError) client #PID<0.779.0> timed out because it checked out the connection for longer than 15000ms"
        ],
        tags: []
      },
      notifier: %{
        language: "elixir",
        name: "honeybadger-elixir",
        url: "https://github.com/honeybadger-io/honeybadger-elixir",
        version: "0.16.0"
      },
      request: %{
        context: %{
          application: :db_connection
        }
      },
      server: %{
        environment_name: :prod,
        hostname: "[REDACTED]",
        project_root: "/app/apps/[REDACTED]",
        revision: nil
      }
    }
  }
}
```

Notice that improper list constructed under the `:error` map's `:message` value:

<img width="1110" alt="Screen Shot 2021-04-15 at 1 52 57 PM" src="https://user-images.githubusercontent.com/957810/114915858-239bed80-9df2-11eb-8f47-b9a7a926f7bc.png">

I was going to try to dig into this further and submit a patch, but I am having troubles getting the dependencies installed for the `honeybadger-elixir` project. I don't know if the improper list in my case is an artifact of how Honeybadger is processing things, or perhaps some log information making its way to Honeybadger from the DB logging. Perhaps adding a guard that ensures the list is a proper list will resolve this (or at least aid in further troubleshooting).

Hope this helps!

**Comment by sorentwo** [comment]
This is very helpful, thank you for the thorough report. This started happening in the past few versions. I'm confident that with a test that replicates the improper list error I can bisect and nail it down.

**Comment by henrik** [comment]
🥳
