### ISSUE TITLE
Can't get filter_args: false to work

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#368]
I've been trying to test out the feature where method arguments are included in the stack trace (see [`filter_args` config option](https://github.com/honeybadger-io/honeybadger-elixir#advanced-configuration)), but can't make it work. What am I doing wrong?

## Steps to Reproduce

1. Bootstrap a new Phoenix app
```shell
# https://hexdocs.pm/phoenix/installation.html
# https://hexdocs.pm/phoenix/up_and_running.html
mix archive.install hex phx_new 1.5.9
mix phx.new hello
cd hello
mix ecto.create
mix phx.server
# or: iex -S mix phx.server
```

2. Install honeybadger package
```elixir
defp deps do
  [{:honeybadger, "~> 0.12"}]
end
```

3. Configure `honeybadger` in `config/config.exs`
```elixir
config :honeybadger,
  api_key: "project API key",
  environment_name: :prod,
  use_logger: false,
  filter_args: false
```

4. Add Honeybadger Plug to `lib/hello_web/router.ex`
```elixir
defmodule HelloWeb.Router do
  use HelloWeb, :router
  use Honeybadger.Plug

  # ...
end
```

5. Edit `lib/hello_web/controllers/page_controller.ex`

```elixir
defmodule HelloWeb.PageController do
  use HelloWeb, :controller
  
  def index(conn, _params) do
    # render(conn, "index.html")
    raise_error(conn, "random string")
  end
  
  defp raise_error(conn, string) do
    raise "test error"
  end
end
```

## Result

No args:

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/474649/122838865-c584fe00-d2ab-11eb-8ef2-0248a8bea92f.png">

I'm expecting to see something like: `raise_error(%{ conn inspect output }, "random string")`

**Comment by TraceyOnim** [comment]
@joshuap I have debugged the issue, here is the stack trace that I'm receiving from my phoenix app , which I'm suspecting is the same stack trace that honey badger might be receiving from your end.
```
{HelloWeb.PageController, :new,  2,
   [file: 'lib/hello_web/controllers/page_controller.ex', line: 8]}
```
In this case , the `args` is received as an integer which represents the arity of the function. 
The `format_args/2` which takes in the `arg` and `filter_args` will always match line [backtrace.ex 56](https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger/backtrace.ex#L56) returning an empty list hence not displaying the function with its argument i.e `raise_error(%{ conn inspect output }, "random string")`

**Comment by joshuap** [comment]
@TraceyOnim ah, I forgot that there are some known cases where the full arguments are not available. Here is some relevant info:

https://github.com/honeybadger-io/honeybadger-elixir/pull/115#issuecomment-350154494
https://github.com/honeybadger-io/honeybadger-elixir/issues/123

I'm going to close this for now, since I now understand why the args aren't being reported in every case. I'll continue to track improvements to this feature in #123.

Thanks for double-checking!
