### ISSUE TITLE
Erlang v18 required

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#38]
I had [crywolf-elixir](https://github.com/honeybadger-io/crywolf-elixir) using Erlang 17 on Heroku and got [this error](https://app.honeybadger.io/fault/44062/f07f29ca1c483a8d2d27e3c220abfe8d) when I upgraded to 0.5.0. Are many people still using v17? I'd say we should either support 17 and 18 or mention in the README that v18 is required. What do you think, @rbishop?

**Comment by rbishop** [comment]
Yes I think we should only support Erlang 18 at this point. I commented on the PR about this. Elixir 1.2 and newer all require Erlang 18 anyway. I'll add something to the README.

**Comment by joshuap** [comment]
Heh, obviously I don't read PR comments >.> Thanks :)

**Comment by nurugger07** [comment]
Added a Prerequisites note on the README for minimum requirements
