### ISSUE TITLE
callback_spec_arg_type_mismatch for Honeybadger.Plug in router

### ISSUE THREAD

**Issue by AdamT** [honeybadger-io/honeybadger-elixir#381]
I just upgraded to plug 1.12.0 and dialyzer is getting this error from Honeybadger.Plug. I have cleaned the project and removed the _build directory.

```
lib/my_app_web/router.ex:3:callback_spec_arg_type_mismatch
The @spec type for the 2nd argument is not a
supertype of the expected type for the handle_errors/2 callback
in the Plug.ErrorHandler behaviour.

Success type:
%{:kind => atom(), :reason => _, :stack => _}

Behaviour callback type:
%{
  :reason => _,
  :stacktrace => [
    {(... -> any), [any()] | non_neg_integer(), Keyword.t()}
    | {atom(), atom(), [any()] | non_neg_integer(), Keyword.t()}
  ],
  :type => :error | :exit | :throw
}

________________________________________________________________________________
lib/my_app_web/router.ex:3:callback_spec_type_mismatch
The @spec return type does not match the expected return type
for handle_errors/2 callback in Plug.ErrorHandler behaviour.

Actual:
@spec handle_errors(...) :: :ok

Expected:
@spec handle_errors(...) :: no_return()

________________________________________________________________________________
```

**Comment by TraceyOnim** [comment]
@sorentwo I could use your help here, the spec for `handle_errors/2` is kinda conflicting. 
For dialyzer to pass successfully in this case, the spec for `handle_errors/2` needs to be defined as follows 
```elixir
handle_errors(Plug.Conn.t(), %{
  type: :error | :throw | :exit,
  reason: Exception.t() | term(),
  stacktrace: Exception.stacktrace()
}) :: no_return()
```
this is how its also defined in the docs 
The conflicting part is that this `handle_errors(Plug.Conn.t(), %{kind: atom(), reason: any(), stack: any()}) :: :ok` is the actual  data that is been used . Some of the keys like `:kind` and `:stack` are not similar to that suggested by dialyzer. 
How can we handle this? Do we stick with the suggested spec?

**Comment by sorentwo** [comment]
@TraceyOnim The docs, and the callback, still look the way we have them defined: https://hexdocs.pm/plug/1.12.1/Plug.ErrorHandler.html#c:handle_errors/2. Regardless, the return value for our spec is wrong (`:ok` rather than `no_return()`).

I think the proper fix here is to replace the `@spec` with `@impl Plug.ErrorHandler`, like this:

```elixir
        @impl Plug.ErrorHandler
        def handle_errors(_conn, %{reason: %FunctionClauseError{function: :do_match}}), do: :ok
```

**Comment by TraceyOnim** [comment]
> @TraceyOnim The docs, and the callback, still look the way we have them defined: https://hexdocs.pm/plug/1.12.1/Plug.ErrorHandler.html#c:handle_errors/2. Regardless, the return value for our spec is wrong (`:ok` rather than `no_return()`).
> 
> I think the proper fix here is to replace the `@spec` with `@impl Plug.ErrorHandler`, like this:
> 
> ```elixir
>         @impl Plug.ErrorHandler
>         def handle_errors(_conn, %{reason: %FunctionClauseError{function: :do_match}}), do: :ok
> ```

Great fix, I can open a PR for this

**Comment by joshuap** [comment]
@TraceyOnim is this done and just needs to be released? If so, I can cut a release. I think the [changelog](https://github.com/honeybadger-io/honeybadger-elixir/blob/master/CHANGELOG.md) needs to be updaed.
