### ISSUE TITLE
logger.ex:24: warning: variable context is unused

### ISSUE THREAD

**Issue by somlor** [honeybadger-io/honeybadger-elixir#39]
Saw these warnings when compiling:
```
lib/honeybadger/logger.ex:24: warning: variable context is unused
lib/honeybadger/logger.ex:27: warning: variable exception is unused
lib/honeybadger/logger.ex:29: warning: variable exception is unused
lib/honeybadger/logger.ex:29: warning: variable stacktrace is unused
```

Forked repo and intended to submit a pull but now I'm scratching my head. Why does Elixir think that these variables are unused? 👀 
```elixir
case error_info do
  {_kind, {exception, stacktrace}, _stack} when is_list(stacktrace) ->
    Honeybadger.notify(exception, context, stacktrace)
  {_kind, exception, stacktrace} ->
    Honeybadger.notify(exception, context, stacktrace)
end
```
https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger/logger.ex#L24

**Comment by rbishop** [comment]
This seems odd to me. Do you get this when compiling in an environment that is not in your `exclude_envs` setting for Honeybadger? We use a macro to disable reporting in excluded environments like `test` and `dev`. I wonder if that could be the cause?

**Comment by somlor** [comment]
Interesting. I don't think so. I get it even when I clone this repo and run `mix test`. Is this just on my end? Let me know if I can provide anymore info. I was running Erlang 18.2.1 with Elixir 1.2.3 but I've just upgraded to 18.3 + 1.2.4 and still seeing warnings.

**Comment by rbishop** [comment]
I can replicate this, too. :+1: I'll look into it.

**Comment by joshuap** [comment]
@rbishop thanks!
