### ISSUE TITLE
Multiple Honeybadger.Metrics.Servers

### ISSUE THREAD

**Issue by KronicDeth** [honeybadger-io/honeybadger-elixir#40]
Joshua asked me to open this issue based on a support ticket for Honeybadger.io.

Our application has an API, that is monitored for response time just fine by the `Honeybadger.Plug`, but the app also gets RPC requests over RabbitMQ.  I'd like to add performance metric for the RPC calls to the servers in the app too, but I want to be able to separate the metrics for the API controllers from the RPC servers.  I want those metrics separate because they are being served by different code and the RPC servers have more rendering, but the API controllers have the time to do authorizations, so I don't want their performance being conflated.

I had considered using a separate environment key for the API and RPC, but [`Honeybadger.Metrics.Server` calls `Honeybadger.Client.new` without any arguments](https://github.com/honeybadger-io/honeybadger-elixir/blob/d17b0bcd723326b16868ca3c0be1ee251cd30e23/lib/honeybadger/metrics/server.ex#L47), so I can't start a separate `Honeybadger.Metric.Server` with a separate `HoneyBadger.Client` configuration.

The `Honeybadger.Metric.Server` could have a `simple_one_for_one` `Supervisor` installed above it that can be used to create additional `Honeybadger.Metric.Server` from multiple `Application` configuration entries or at runtime as described [here](http://elixir-lang.org/docs/stable/elixir/Supervisor.html#start_child/2).  Then each `Honeybadger.Metric.Server` would have state that was passed to `Honeybadger.Client.new`, which would have to change to accept arguments.

This is one proposal, it's your library, so you can figure out if some other setup works better for the website's backend.

**Comment by joshuap** [comment]
@KronicDeth thanks again for the suggestion. Adding the "enhancement" label and will look into this in the future.

**Comment by joshuap** [comment]
Closing this for now. See http://blog.honeybadger.io/sunsetting-performance-metrics/
