### ISSUE TITLE
The user agent should include the package version

### ISSUE THREAD

**Issue by stympy** [honeybadger-io/honeybadger-elixir#408]

**Comment by joshuap** [comment]
Hi @TraceyOnim, the user agent is here:

https://github.com/honeybadger-io/honeybadger-elixir/blob/bff1531643003a03c68b7f8d083e9a1a2f3fe434/lib/honeybadger/client.ex#L11

That string is used as the `User-Agent` header when making requests to our API. What we want is to include the package version info, so our API knows where version of the package is making each request. It should look the same as the `User-Agent` for our Ruby gem, i.e. "HB-Elixir 0.19.0":

https://github.com/honeybadger-io/honeybadger-ruby/blob/f0d3057ad90bcd442ee052aca12811b78c35fbe0/lib/honeybadger/util/http.rb#L21

**Comment by TraceyOnim** [comment]
Thank you @joshuap for the clarification.
