### ISSUE TITLE
Does honeybadger-elixir catch errors on processes launched with spawn?

### ISSUE THREAD

**Issue by jaimeiniesta** [honeybadger-io/honeybadger-elixir#43]
If a process launched via `spawn` crashes, will the error be reported? I mean, not using `Task.async`, just `spawn`.

**Comment by rbishop** [comment]
Nope. The process needs to be a Special Process in order for the error logger to pick it up. Here's some more info on that http://erlang.org/documentation/doc-4.9.1/doc/design_principles/spec_proc.html
