### ISSUE TITLE
Warnings when compiling under Elixir 1.3

### ISSUE THREAD

**Issue by derekprior** [honeybadger-io/honeybadger-elixir#45]
```
==> honeybadger
Compiling 11 files (.ex)
warning: variable session is unused
  lib/honeybadger/plug.ex:50

warning: variable e is unused
  lib/honeybadger/plug.ex:52

warning: unused import Supervisor.Spec
  lib/honeybadger.ex:106

warning: variable context is unused
  lib/honeybadger/logger.ex:24

warning: variable exception is unused
  lib/honeybadger/logger.ex:27

warning: variable exception is unused
  lib/honeybadger/logger.ex:29

warning: variable stacktrace is unused
  lib/honeybadger/logger.ex:29

Generated honeybadger app
```

**Comment by nurugger07** [comment]
@derekprior thanks! I'm going to look at the upgrade to Elixir v1.3 this weekend. Is everything else working well then?

**Comment by derekprior** [comment]
I haven't deployed to production or staging yet, but locally it's checking out. I even have a branch where I started addressing those warnings, but the one for unused variable `context` is perplexing because it does look like it's used. Granted, I spent only 5 minutes looking at it so far.

**Comment by nurugger07** [comment]
This should be resolved after the merge. I'll get @joshuap to push up a hex update :) Thanks to @mitchellhenke for the PR!

**Comment by mitchellhenke** [comment]
@nurugger07 do you think a new release will be made soon?

**Comment by nurugger07** [comment]
@mitchellhenke I'll be working on getting it out this week. I wanted to get a little more in :)

**Comment by mitchellhenke** [comment]
@nurugger07 sounds perfect, thank you!

**Comment by nurugger07** [comment]
v0.6 was released and the warnings have been cleaned up. Special thanks to @mitchellhenke :)

**Comment by mitchellhenke** [comment]
@nurugger07 you bet!
