### ISSUE TITLE
Include source snippets in backtrace

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#466]
We should include a snippet of the source code for each line of the backtrace, like we do for Ruby, JavaScript, and others.

- [honeybadger-ruby](https://github.com/honeybadger-io/honeybadger-ruby/blob/3bd7d05e368340f9cc14edc6ccf3144dd9661765/lib/honeybadger/backtrace.rb#L82) (and [here](https://github.com/honeybadger-io/honeybadger-ruby/blob/3bd7d05e368340f9cc14edc6ccf3144dd9661765/lib/honeybadger/backtrace.rb#L135))
- [honeybadger-js](https://github.com/honeybadger-io/honeybadger-js/blob/cc7afa1435f2c824a076a43d8727db0b46d91970/packages/core/src/client.ts#L193)
- [notice schema](https://github.com/honeybadger-io/honeybadger-schemas/blob/77bcff997132d5393b51db26d1cc77efd6f0dc88/exceptions/v1/notices.json#L165)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hzazl)

**Comment by sorentwo** [comment]
This is a problem because Elixir is a compiled language and there isn’t any guarantee (most likely not) that the source is still available.

**Comment by joshuap** [comment]
> This is a problem because Elixir is a compiled language and there isn’t any guarantee (most likely not) that the source is still available.

Ah yes, that makes sense. I guess we could pull the info from GitHub in the future (we currently link to GitHub from the backtrace, vs. displaying the code inline).

**Comment by trashhalo** [comment]
>Ah yes, that makes sense. I guess we could pull the info from GitHub in the future (we currently link to GitHub from the backtrace, vs. displaying the code inline).

That was my thought as well. You already know the exact line and commit to link to at github. If you had access to github repo you could just pull down the source and show it.
