### ISSUE TITLE
Making private functions (handle_errors/2 in this case) overridable is deprecated

### ISSUE THREAD

**Issue by enilsen16** [honeybadger-io/honeybadger-elixir#47]
with Elixir: 1.4-dev and Phoenix 1.2 --
```
warning: making private functions (handle_errors/2 in this case) overridable is deprecated
  (elixir) lib/module.ex:842: anonymous fn/2 in Module.make_overridable/2
  (stdlib) lists.erl:1338: :lists.foreach/2
  web/router.ex:3: (module)
  (elixir) src/elixir_compiler.erl:125: :elixir_compiler.dispatch_loaded/6
  (elixir) src/elixir_module.erl:192: :elixir_module.eval_form/6
```

From this commit in Elixir -- https://github.com/elixir-lang/elixir/commit/3db142763438b5120ed48d1997b0264d72402df9

**Comment by nurugger07** [comment]
Thanks for letting us know but unfortunately this isn't a honeybadger-elixir issue. The warning message is coming from the private overridable functions in the Plug dependency. However, I did submit a PR to Plug that will remove the warnings but I'm not sure if/when it will be accepted. That being said the Honeybadger client hasn't been test against the 1.4.0-dev release.

We will continue to prepare for the 1.4 release but I'm closing this issue for now.

**Comment by enilsen16** [comment]
Thanks I didn't realize it was on Plug. 👍
