### ISSUE TITLE
:breadcrumbs_enabled blowing up logs, consider putting elsewhere

### ISSUE THREAD

**Issue by trashhalo** [honeybadger-io/honeybadger-elixir#475]
Our logs go to datadog and we use logging metadata to send extra context. Since turning on breadcrumbs its breaking logs when the data in hb_breadcrumbs is large enough to split the json line across multiple lines.

There doesnt seem to be a way to use breadcrumbs but move their storage out of the logger context. For now we have disabled breadcrumbs even though they add a ton of value.

**Comment by subzero10** [comment]
@trashhalo, this should be fixed with [v0.20.0](https://hex.pm/packages/honeybadger)!

cc @sorentwo
