### ISSUE TITLE
Incorrect "Mandatory config key :api_key not set" popping up in excluded envs

### ISSUE THREAD

**Issue by florish** [honeybadger-io/honeybadger-elixir#496]
Hi, I'm just getting started with Honeybadger in an Elixir/Phoenix app. Works great!

Minor thing is that I see this error popping up on application startup in `dev` and `test` environments:

```
[error] [Honeybadger] Mandatory config key :api_key not set
```

While I understand the idea, in our case, we deliberately _only_ set the `HONEYBADGER_API_KEY` env var in `prod` environments. Reason for this is twofold:

* The default configuration `excluded_envs: [:dev, :test]` already disables Honeybadger in the other two default `mix phx.new`-generated environments, so setting the API keys there does not actually make sense.
* This avoids us from having to store a secret in our Git repository (we define our `prod` env vars in a secure store).

For now, my workaround is to set a fake API key value in `config/config.exs`, e.g.:

```
config :honeybadger, api_key: ""
```

While this works, I'm opening this issue as I believe the error is a bit confusing in combination with the default of _disabling_ Honeybadger in `dev` and `test`.

**Comment by florish** [comment]
Ok, sorry for spamming, but I've been misguiding myself with my assumption about the default `:environment_name` value in the Honeybadger config.

The [configuration docs](https://docs.honeybadger.io/lib/elixir/#configuration) are actually perfectly clear that the default value is `:prod`:

environment_name | (required) The name of the environment your app is running in. | :prod
-- | -- | --

In combination with the default value of `exclude_envs: [:dev, :test]`, however, I was in the assumption that Honeybadger would also use `Mix.env()` or [`config_env()`](https://hexdocs.pm/elixir/Config.html#config_env/0) to automatically set `:environment_name` to the current configuration environment.

After changing my config to this:

```
config :honeybadger, environment_name: config_env()
```

The `[error]` and `[warning]` messages when running `mix test` runs are gone, even with `:api_key` not set to a thruthy value (and `HONEYBADGER_API_KEY` also not in place).

Again, my apologies for jumping to conclusions. As this no longer seems to be an issue, but maybe only a feature request to change the default for `:environment_name` to `config_env()`, I'm closing this one.

**Comment by subzero10** [comment]
Hey @florish, I'm glad that you sorted it out!
