### ISSUE TITLE
Honeybadger.Plug calls server multiple times when reporting an error

### ISSUE THREAD

**Issue by cmwilhelm** [honeybadger-io/honeybadger-elixir#52]
RE: PR #51 

Copied and pasted from the failing test case in the PR:

When using the Honeybadger plug, it seems that multiple attempts to call Honeybadger are being performed.

This PR serves to demonstrate the problem with a failing test case, by setting up a Bypass server standing in for Honeybadger API. This server appears to receive messages twice from the plug machinery.

(Most of the test code exists to inject new configuration after the compilation of the existing PlugApp so that exclude_envs is meaningly overridden.)

I was unable to reproduce this problem by calling Honeybadger.notify directly.

**Comment by nurugger07** [comment]
@cmwilhelm I've noticed this in testing too. I'm working on making some major changes to the test suite and it should remove the additional calls.

**Comment by nurugger07** [comment]
This is resolved in the v0.6.2 release
