### ISSUE TITLE
Replace `Plug.Adapters.Cowboy` with `Plug.Cowboy`

### ISSUE THREAD

**Issue by abshierjoel** [honeybadger-io/honeybadger-elixir#524]
Plug has moved `Plug.Adapter.Cowboy` into `Plug.Cowboy` with version `2.0`. This is listed in the changelog [here](https://hexdocs.pm/plug_cowboy/changelog.html#v2-0-0-2018-10-20). I believe the only place this is being used currently is `test_helper.exs`.

**Comment by subzero10** [comment]
Released with `0.21.0`!
