### ISSUE TITLE
exq integration

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#54]
This integration would automatically report exceptions from failed exq jobs, similar to how we do for Ruby/Sidekiq. See https://github.com/akira/exq/issues/191 for a potential solution. We should also investigate if the current `use_logger` option already works for this case.

**Comment by rbishop** [comment]
I've had this discussion pop up a few other times about other background job libraries in Elixir. In general the problem I've noticed is that most of them are designed like Ruby libraries and not like Erlang/Elixir libraries. What I mean is that when an exception occurs they rescue it and do their cleanup. If they were to re-raise after cleanup then the process will crash and the error logger will be automatically notified.

**Comment by schneidmaster** [comment]
I confirmed that `use_logger` does not work with exq. I wrote a very simple [middleware](https://gist.github.com/schneidmaster/9db15d6c897e46798e3645eeac2864ba) that ought to do the trick, but haven't tested it yet since the [change](https://github.com/akira/exq/pull/205) to make the exception struct available in exq middleware hasn't yet landed in a stable release.

**Comment by schneidmaster** [comment]
Two other notes on exq middleware --

* It must be declared in `config.exs` in addition to the default exq middleware; i.e. you need `middleware: [Exq.Middleware.Stats, Exq.Middleware.Job, Exq.Middleware.Manager, Exq.Middleware.Logger, Exq.Middleware.Honeybadger]` or else the Stats, Job, etc. won't run. AFAIK there's no way to declare "extra" middleware without re-declaring the default list.

* The `before_work` and `after_processed_work` methods are required in all exq middleware even if they just return the unadulterated pipeline

**Comment by joshuap** [comment]
@schneidmaster thanks! We'll keep an eye on the exq release so that we can potentially package an error-handling middleware with honeybadger.

**Comment by sorentwo** [comment]
There are more than a handful of background job processors out there now: exq, verk, ecto_job, honeydew, kiq. There isn't an obvious favorite to support like there is with plug and phoenix.

I don't believe it is tenable to support middleware for all of these projects inside of Honeybadger itself (not to mention how easy it is to integrate Honeybadger manually).

@joshuap What do you think? Can we close this out?

**Comment by joshuap** [comment]
@sorentwo yep, thanks!
