### ISSUE TITLE
Filter out sensitive request parameters

### ISSUE THREAD

**Issue by totallymike** [honeybadger-io/honeybadger-elixir#55]
It doesn't appear that this library has the ability to filter sensitive request parameters. I'm seeing passwords in our HB error reports.

Is there something I'm missing, or an available workaround to filter out various headers and parameters from being logged to Honeybadger?

**Comment by joshuap** [comment]
We don't have this feature yet for Elixir, but we can add it to the roadmap. PRs are also welcome (just let me know if anyone decides to take it on so that we don't duplicate effort).

**Comment by rranelli** [comment]
We would like to filter out the cookie header when reporting errors. Still no way to do that?

**Comment by joshuap** [comment]
@rranelli not yet, but we might be able to add that to #62. I'll mention it over there.

**Comment by joshuap** [comment]
This is now possible using the new filter feature (see #62). I think adding "HTTP_COOKIE" to the default `filter_keys` config would work, or you can also create a custom notice filter with the `filter_cgi_data` callback.
