### ISSUE TITLE
masking sensitive values in reports

### ISSUE THREAD

**Issue by mmmries** [honeybadger-io/honeybadger-elixir#60]
Is there any support or planned support for being able to mask sensitive values in honeybadger reports? Or is there another way to pay into sasl reports so I can mask values there before they get sent to honeybadger?

In my use case there are `GenServer`s that hold sensitive credentials in-memory to keep them hidden from the rest of the application, but if they fail the default error reports will include information about the state of the GenServer when it failed and that will include these sensitive credentials.

Maybe there's a standard way to handle this in OTP so it gets resolved before honeybadger gets involved? Any guidance would be very helpful

**Comment by joshuap** [comment]
@mmmries this is in the works; see #55 and #62. Are you talking about sensitive values appearing in the context? I didn't think we were sending state from a `GenServer` by default. Is that something you're adding manually?

**Comment by mmmries** [comment]
@joshuap thanks for following up. The only sensitive data I've seen come through so far was phoenix params. I thought GenServer state might come through because SASL logs locally show that data, but I haven't actually seen those come through so far. If you are already skipping that data then it shouldn't be a problem.

Do you log the `last_message` that caused a GenServer to fail? That might contain sensitive data in my use case as well.

**Comment by joshuap** [comment]
I don't believe we do; you should be good as long as params and context are filtered.
