### ISSUE TITLE
Remove metrics reporting

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#63]
See http://blog.honeybadger.io/sunsetting-performance-metrics/

This should remove the code that was added in #25 (and anything related that was added since then). This should also fix #44, since there will no longer be a `Metrics.Server` to crash.

**Comment by nurugger07** [comment]
This will be coming on the v0.7 release later this week. I have a branch with the Metrics Server functionality removed but looking to implement the notifications as supervised gen_servers.

**Comment by mwoods79** [comment]
PR here https://github.com/honeybadger-io/honeybadger-elixir/pull/80
