### ISSUE TITLE
Infinite errors logged

### ISSUE THREAD

**Issue by pdilyard** [honeybadger-io/honeybadger-elixir#65]
After a period of time (days-weeks), we'll notice things stop working in our production application. There are 500s happening, but no errors are reported to Honeybadger. I attach to the running error logs, and all I see is constant scrolling of errors originating in the HB lib. Here's a sample:

```
15:43:32.141 [error] Task #PID<0.14798.3740> started from :error_logger terminating
** (ArgumentError) argument error
    (honeybadger) lib/honeybadger/client.ex:36: Honeybadger.Client.send_notice/3
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.116999615/0 in Honeybadger.Logger.handle_event/2>
    Args: []

=CRASH REPORT==== 27-Oct-2016::15:43:32 ===
  crasher:
    initial call: Elixir.Honeybadger.Logger:-handle_event/2-fun-0-/0
    pid: <0.14798.3740>
    registered_name: []
    exception exit: {badarg,
                        [{'Elixir.Honeybadger.Client',send_notice,3,
                             [{file,"lib/honeybadger/client.ex"},{line,36}]},
                         {'Elixir.Task.Supervised',do_apply,2,
                             [{file,"lib/task/supervised.ex"},{line,94}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,247}]}]}
      in function  'Elixir.Task.Supervised':exit/4 (lib/task/supervised.ex, line 125)
    ancestors: [error_logger,<0.3.0>]
    messages: []
    links: []
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 13795
  neighbours:
```

I have no idea if this is actually caused by this library, or if it is caused by something else. If it's caused by something else, I have no way of knowing because the logs are immediately clogged with the above message.

Any help would be much appreciated.

**Comment by nurugger07** [comment]
@pdilyard Can you provide some more detail like is this a Phoenix, Plug, or other application and if so the version. Also, what version of the HB lib are you using? Are you doing any thing custom in the setup or is it just a default configuration. The more detail you can provide the easier it is to troubleshoot/replicate the issue.

**Comment by pdilyard** [comment]
Elixir version: `1.3.2`
Honeybadger version: `0.6.1`
It is a Phoenix application, Phoenix version: `1.2.0`

This is my config:
```elixir
config :honeybadger,
  environment_name: :prod,
  use_logger: true,
  api_key: "honeybadger api key"
```
(I know this config is correct because it would successfully post errors most of the time. Eventually it would get into the state described above and stop posting errors to HB)

The only other file that touches HB in my project is in my `web.ex` file:
```elixir
  def router do
    quote do
      use Phoenix.Router
      use Honeybadger.Plug
    end
  end
```
(This is including by adding `use Web, :router` to my `router.ex` file.

Let me know if I can help in any other way.

**Comment by mbriggs** [comment]
same thing happening here, same setup.

**Comment by mbriggs** [comment]
some more info: I seem to be triggering this on the first error after an upgrade release (distillery / gatling) on production. fills up 5 log files worth of what was previously reported. if i restart the app, it works as expected

**Comment by mwoods79** [comment]
@pdilyard @mbriggs We released 0.6.3 please let us know if this is still happening.

**Comment by belousovAV** [comment]
Still problem
`"honeybadger": {:hex, :honeybadger, "0.6.3"`

```
=CRASH REPORT==== 30-Jun-2017::08:47:20 ===

  crasher:

    initial call: Elixir.Honeybadger.Logger:-handle_event/2-fun-0-/0

    pid: <0.3584.4420>

    registered_name: []

    exception exit: {badarg,

                        [{'Elixir.Honeybadger.Client',do_send_notice,4,

                             [{file,"lib/honeybadger/client.ex"},{line,37}]},

                         {'Elixir.Task.Supervised',do_apply,2,

                             [{file,"lib/task/supervised.ex"},{line,85}]},

                         {proc_lib,init_p_do_apply,3,

                             [{file,"proc_lib.erl"},{line,247}]}]}

      in function  'Elixir.Task.Supervised':exit/4 (lib/task/supervised.ex, line 116)

    ancestors: [error_logger,<0.5.0>]

    message_queue_len: 0

    messages: []

    links: []

    dictionary: []

    trap_exit: false

    status: running

    heap_size: 6772

    stack_size: 27

    reductions: 27058

  neighbours:

08:47:20.922 [error] Task #PID<0.3585.4420> started from :error_logger terminating

** (ArgumentError) argument error

    (honeybadger) lib/honeybadger/client.ex:37: Honeybadger.Client.do_send_notice/4

    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2

    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

Function: #Function<0.6768666/0 in Honeybadger.Logger.handle_event/2>

    Args: []
```

**Comment by sorentwo** [comment]
I think that with #93 and #109 this issue shouldn't be an issue anymore.

@belousovAV @pdilyard @mbriggs if you happen to be using honeybadger still, will you check whether this problem still exists on master?

**Comment by belousovAV** [comment]
Do not see this error either with 0.6.3 or with master.

**Comment by joshuap** [comment]
Awesome. I'm going to go ahead and close this so that we can do the 0.7 release. If any of you experience this again, please reopen and we'll continue digging.
