### ISSUE TITLE
Relax Poison Version

### ISSUE THREAD

**Issue by codeithuman** [honeybadger-io/honeybadger-elixir#66]
If honeybadger could run on versions 2 of poison, that'd be awesome. I'm using Phoenix 1.2.1 and it requires poison v2. 

When running `mix deps.update --all`:
>
Failed to use "poison" (version 2.2.0) because
  ecto (version 2.1.0-rc.3) requires ~> 2.2 or ~> 3.0
  ex_aws (version 1.0.0-rc.4) requires ~> 1.2 or ~> 2.0
  honeybadger (version 0.6.2) requires ~> 3.0
  phoenix (versions 1.2.0 and 1.2.1) requires ~> 1.5 or ~> 2.0

Honeybadger is the conflicting package that does not support poison v2.

**Comment by mwoods79** [comment]
Sounds reasonable https://github.com/honeybadger-io/honeybadger-elixir/pull/75
