### ISSUE TITLE
Not catching errors in channels

### ISSUE THREAD

**Issue by axelson** [honeybadger-io/honeybadger-elixir#67]
Trying to set this up today and it is working fine in the PagesController but I am completely unable to get it working with Channels. Is there something additional I need to configure? Am I missing anything?

**Comment by nurugger07** [comment]
@axelson this should be working in channels. I'll take a look today in the test app we have. Can you provide the version #s for Elixir/Phoenix/Honeybadger-elixir that you are using?

**Comment by axelson** [comment]
* Elixir 1.3.4 `Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]`
* Phoenix 1.2.1
* honeybadger 0.6.1

**Comment by markquezada** [comment]
@nurugger07 Hey Johnny, did you happen to test this? (Hello again BTW!) Anything we can do to help?

**Comment by mwoods79** [comment]
@axelson do you have an example of how you were calling `HoneyBadger.notify` in your channel(s)?

**Comment by axelson** [comment]
@mwoods79 I'm not manually calling `HoneyBadger.notify` in the channels, just hoping that uncaught exceptions are caught and sent to honeybadger.

**Comment by madshargreave** [comment]
Status one this?

**Comment by mwoods79** [comment]
@madshargreave exceptions are not automatically caught in channels. For logging you need to manually call `HoneyBadger.notify`.
