### ISSUE TITLE
Add the ability to pass in a proxy config for HTTPoison

### ISSUE THREAD

**Issue by cbarratt** [honeybadger-io/honeybadger-elixir#68]
Currently this library isn't usable in a corporate / heavy firewall'd environments where you'd typically need a proxy to get outside of the network.

I'll take a look to see if I can butcher together a PR for this! But it's definitely a requirement at the company I work for :) Looking forward to using this library as Honeybadger is great!

**Comment by joshuap** [comment]
Sorry for the delay! I would definitely accept a PR for this, or we can look into it at some point. We should be ramping up development on the Elixir client again soon.

**Comment by cbarratt** [comment]
I did create a very quick PR on this - it does work functionally but I would appreciate feedback :)

https://github.com/honeybadger-io/honeybadger-elixir/pull/69

**Comment by mwoods79** [comment]
https://github.com/honeybadger-io/honeybadger-elixir/pull/69 was merged.
