### ISSUE TITLE
Remove meck in favor of an API stub

### ISSUE THREAD

**Issue by rbishop** [honeybadger-io/honeybadger-elixir#7]
Using `meck` for mocking is kind of weird and unnatural. It's easier and cleaner to just stand up a simple Plug app with a `notify` route and change the `origin` config for the test environment. We will probably also need to add Cowboy as a test dependency.

**Comment by joshuap** [comment]
:+1:

**Comment by dpehrson** [comment]
@rbishop It may be worth looking into [Bypass](https://github.com/PSPDFKit-labs/bypass)

I've used it a bit and while there is room for improvement, if you're not doing anything that requires coordinating lots of outgoing requests, it's probably a lighter weight solution.
