### ISSUE TITLE
Track parameters from function invocations

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#78]
In some cases it appears that a backtrace can include the parameters used to invoke a function that caused an error. Example:

```
2017-03-01T16:53:52.772605+00:00 app[web.1]: (my_web) web/controllers/gateway_controller.ex:126: MyWeb.GatewayController.my_function("", nil, 608, 2) 
```

It would be cool if we could capture these and display them in Honeybadger.

**Comment by duff** [comment]
👍 Thanks Josh!

**Comment by sorentwo** [comment]
@joshuap I did a little research spike on this and it looks rather straight forward. Do you have a preferred/suggested format for reporting arguments? Looking at the Ruby gem's implementation didn't provide any insight.

**Comment by joshuap** [comment]
@sorentwo for reference, [here is our collector API documentation](http://docs.honeybadger.io/guides/api.html#collector-api). I'm thinking that we'd add some new property to the backtrace, such as  `.error.backtrace[].params`:

```
{
  "error":{
    "class":"RuntimeError",

    # ...

    "backtrace":[
      {
        "number":"4",
        "file":"web/controllers/gateway_controller.ex",
        "method":"my_function",
        "params": ["", nil, 608, 2]
      },

      # ..

    ]

    # ...

}
```

What do you think?

**Comment by joshuap** [comment]
cc @stympy -- thoughts on this?

**Comment by sorentwo** [comment]
@joshuap Adding a new entry for `params` sounds good to me, provided long as the server will safely accept those.

**Comment by joshuap** [comment]
Agreed. We can add support on the server; my only concern is leaking sensitive data. This should probably be an optional feature, or maybe integrate with the request filters somehow.

**Comment by sorentwo** [comment]
An argument could be anything, even a very sizable struct like a `Plug.Conn`, which itself could have contain sensitive data. Additionally, there isn't any way to be sure what a particular argument is, so it could be a name and password, but without any type of label.

I think it should be an opt-in feature with caveats about sensitive information.

This is definitely something I would opt into for the primary app I run, as it doesn't handle any sensitive info (passwords, payment) but knowing the args passed would be very helpful.

**Comment by stympy** [comment]
This looks good to me.  Is params always going to be an array, even when just one arg is passed to the function?  Consider this question a 👍 for it always being an array. 😄
