### ISSUE TITLE
Honeybadger.notify differences between test and prod

### ISSUE THREAD

**Issue by iconpin** [honeybadger-io/honeybadger-elixir#79]
Hi there,

We've been using the module in one of our projects, and one thing that caught my attention is that `Honeybadger.notify` returns something different depending if it's an active environment or not.

This will match only when the environment is active (by default, `:prod`):

```
{:ok, _pid} = Honeybadger.notify("an error")
```

This will match only when the environment is inactive (`:dev` and `:test` by default):

```
:ok = Honeybadger.notify("an error")
```

I'm relatively new to Elixir so this might be the right thing to do, but it's seems a bit weird to me that the return value changes between testing/development and production. In our final code we don't pattern match against `Honeybadger.notify` return, but while developing it was an odd surprise.

Another problem, is that, for example, `Poison` serialization problems can go unnoticed while testing since there's no interaction with the `Client` module at all.

Was this intentional? Do you think it'd make sense to move the logic deeper, so we get better dev/prod parity? I'd be happy to work on a PR for that.

**Comment by joshuap** [comment]
@iconpin I think it would make sense for the behavior to be the same between environments. Ideally I like to have as much functionality as possible in dev mode so that problems are surfaced earlier; the only thing that *shouldn't* happen in dev mode is for the notification to actually be sent. @mwoods79 thoughts?

I'd be happy to take a look at a PR, although note that we're currently making some big changes in #80.

**Comment by mwoods79** [comment]
@joshuap That seems inconsistent. Currently we are running the `Honeybadger.notify/2` async (in a task) for production but synchronously for all other environments. We could wait for the `task` to finish in all non `:prod` environments. Then all environments run the exact same code (except waiting for the task to finish).

**Comment by joshuap** [comment]
Is there a reason we need to wait for the task to finish in development? What if we just always spawn the task, but skip the POST call in `Client` (or wherever makes sense) when not in an active environment?

**Comment by iconpin** [comment]
Since there seems to be agreement, I've played a bit with the code :). If someone can have a look at #83, that would be great!

**Comment by mwoods79** [comment]
Thanks @iconpin
