### ISSUE TITLE
0.6.3 release?

### ISSUE THREAD

**Issue by mmmries** [honeybadger-io/honeybadger-elixir#81]
Are there any plans to do a release before `0.7`? I would love to have a release that includes the new `filter_keys` feature. I'm willing to point to the master branch for now, but it would be really nice to use a hex version instead.

**Comment by joshuap** [comment]
@mmmries I'll see what I can do; a 0.6.3 release might be doable.

**Comment by mmmries** [comment]
My team has been pointed to the master branch now and we've really enjoyed the ability to filter some of the data before it gets reported to honeybadger. If there's any issues that you need to get resolved before a release feel free to mention them here and I'll try to help out as best I can.

Much ❤️ 💛 💙 💚 💜  for an awesome tool!

**Comment by asummers** [comment]
Curious if there's been any movement on getting this up on Hex.

**Comment by joshuap** [comment]
0.6.3 has been released!

**Comment by mmmries** [comment]
Woot! Thanks guys!
