### ISSUE TITLE
httpoison dependency out of date

### ISSUE THREAD

**Issue by drewblas** [honeybadger-io/honeybadger-elixir#85]
The current release is tied to httpoison `~> 0.9`.  However, that release is old, and it is pinned to hackney `~> 1.6.6`.  That release of hackney had a severe bug and was revoked. The bug is fixed in `1.7.0` and up, but there's no way to get hackney 1.7.0 (without an override) because of this dependency chain.

**Comment by mwoods79** [comment]
This should fix: https://github.com/honeybadger-io/honeybadger-elixir/pull/86
