### ISSUE TITLE
First three lines of stack trace are noise when Honeybadger.notify is used

### ISSUE THREAD

**Issue by minhajuddin** [honeybadger-io/honeybadger-elixir#99]
When Honeybadger.notify is used, it adds the following stack trace. The first 3 lines here come from the Honeybadger client code. This occurs in 0.7.0-beta

```
process.ex  640  info(...)
honeybadger.ex  239  backtrace(...)
honeybadger.ex  157  notify(...)
page_controller.ex  8  index(...)
page_controller.ex  1  action(...)
page_controller.ex  1  phoenix_controller_pipeline(...)
```

**Comment by sorentwo** [comment]
How was `notify/1|2|3` called for this example? Was there an error during the request or was it triggered manually? That is expected if `Honeybadger.notify/1|2` is called manually, without the stacktrace being passed in.

When no stacktrace is provided it falls back to using `Process.info/2` (http://erlang.org/doc/man/erlang.html#process_info-2) , which will always contain some "noise" about the caller at the top of the stack. It doesn't make a difference if `Process.info/2` is called from a function or a macro, the extra lines will be prepended. The only way to get a "clean" trace is in the scope of a `try` expression (http://erlang.org/doc/man/erlang.html#get_stacktrace-0).

After writing all this up I realized that `notify` could generate better traces by default, which is implemented in #100

**Comment by minhajuddin** [comment]
`notify` was called manually in this instance.

**Comment by joshuap** [comment]
@minhajuddin can you check out #100 and see if that resolves this issue?
